package net.goutros.goutrosstrangebiomes.worldgen.terrain;

import net.goutros.goutrosstrangebiomes.worldgen.api.TerrainGenerationAPI;
import net.goutros.goutrosstrangebiomes.worldgen.api.BiomeTerrainProvider;
import net.goutros.goutrosstrangebiomes.worldgen.api.BiomeBlockProvider;
import net.minecraft.core.BlockPos;
import net.minecraft.resources.ResourceKey;
import net.minecraft.util.Mth;
import net.minecraft.world.level.biome.Biome;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.chunk.ChunkAccess;
import net.minecraft.world.level.levelgen.Heightmap;
import net.minecraft.world.level.levelgen.RandomState;
import net.minecraft.world.level.levelgen.synth.SimplexNoise;
import net.minecraft.util.RandomSource;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.HashMap;
import java.util.Map;

/**
 * Main terrain generator that blends custom terrain with vanilla
 */
public class BlendedTerrainGenerator {

    private static final Logger LOGGER = LoggerFactory.getLogger("BlendedTerrainGenerator");
    private static final int SEA_LEVEL = 63;
    private static final ThreadLocal<SimplexNoise> BLEND_NOISE = ThreadLocal.withInitial(
            () -> new SimplexNoise(RandomSource.create(12345L))
    );

    /**
     * Generate blended terrain for a chunk
     * Phase 1: Generate vanilla terrain
     * Phase 2: Carve custom terrain shapes with smooth blending
     * Phase 3: Apply custom blocks with biome-based blending
     */
    public static void generateBlendedTerrain(ChunkAccess chunk, RandomState randomState) {
        // Phase 1: Vanilla terrain is already generated by vanilla system

        // Phase 2: Carve custom terrain shapes
        carveCustomTerrainShapes(chunk, randomState);

        // Phase 3: Apply custom blocks
        applyCustomBlocks(chunk, randomState);

        // Update heightmaps
        updateHeightmaps(chunk);
    }

    /**
     * Phase 2: Carve custom terrain shapes with smooth vanilla blending
     */
    private static void carveCustomTerrainShapes(ChunkAccess chunk, RandomState randomState) {
        int minY = chunk.getMinBuildHeight();
        int maxY = chunk.getMaxBuildHeight();

        for (int x = 0; x < 16; x++) {
            for (int z = 0; z < 16; z++) {
                int worldX = chunk.getPos().getMinBlockX() + x;
                int worldZ = chunk.getPos().getMinBlockZ() + z;

                // Calculate biome influences at this position
                Map<ResourceKey<Biome>, Double> biomeInfluences = calculateBiomeInfluences(chunk, x, z, worldX, worldZ);

                if (!biomeInfluences.isEmpty()) {
                    // Generate terrain column with custom shapes
                    generateTerrainColumn(chunk, x, z, worldX, worldZ, biomeInfluences, randomState, minY, maxY);
                }
            }
        }
    }

    /**
     * Generate terrain column with custom shapes blended with vanilla
     */
    private static void generateTerrainColumn(ChunkAccess chunk, int x, int z, int worldX, int worldZ,
                                              Map<ResourceKey<Biome>, Double> biomeInfluences,
                                              RandomState randomState, int minY, int maxY) {

        // Get vanilla surface height as baseline
        int vanillaSurfaceHeight = chunk.getHeight(Heightmap.Types.WORLD_SURFACE_WG, x, z);

        // Calculate custom terrain height
        double customHeight = calculateCustomTerrainHeight(worldX, worldZ, vanillaSurfaceHeight, biomeInfluences, randomState);

        // Generate terrain column with density-based approach
        for (int y = minY; y < maxY; y++) {
            BlockPos pos = new BlockPos(x, y, z);

            // Calculate vanilla density (simplified)
            double vanillaDensity = calculateVanillaDensity(worldX, y, worldZ, vanillaSurfaceHeight);

            // Calculate custom density
            double customDensity = calculateCustomDensity(worldX, y, worldZ, vanillaDensity, biomeInfluences, randomState);

            // Place or remove blocks based on density
            if (customDensity > 0.0) {
                // Place stone for now (blocks will be replaced in phase 3)
                chunk.setBlockState(pos, Blocks.STONE.defaultBlockState(), false);
            } else {
                // Remove block or place air
                if (y <= SEA_LEVEL) {
                    chunk.setBlockState(pos, Blocks.WATER.defaultBlockState(), false);
                } else {
                    chunk.setBlockState(pos, Blocks.AIR.defaultBlockState(), false);
                }
            }
        }
    }

    /**
     * Calculate custom terrain height with smooth blending
     */
    private static double calculateCustomTerrainHeight(int worldX, int worldZ, int vanillaHeight,
                                                       Map<ResourceKey<Biome>, Double> biomeInfluences,
                                                       RandomState randomState) {
        double totalHeight = vanillaHeight;
        double totalInfluence = 0.0;

        for (Map.Entry<ResourceKey<Biome>, Double> entry : biomeInfluences.entrySet()) {
            ResourceKey<Biome> biome = entry.getKey();
            double influence = entry.getValue();

            BiomeTerrainProvider provider = TerrainGenerationAPI.getTerrainProvider(biome);
            if (provider != null) {
                double customHeight = provider.getTerrainHeight(worldX, worldZ, vanillaHeight, influence, randomState);
                totalHeight += (customHeight - vanillaHeight) * influence;
                totalInfluence += influence;
            }
        }

        return totalHeight;
    }

    /**
     * Calculate custom density with smooth blending
     */
    private static double calculateCustomDensity(int worldX, int y, int worldZ, double vanillaDensity,
                                                 Map<ResourceKey<Biome>, Double> biomeInfluences,
                                                 RandomState randomState) {
        double totalDensity = vanillaDensity;

        for (Map.Entry<ResourceKey<Biome>, Double> entry : biomeInfluences.entrySet()) {
            ResourceKey<Biome> biome = entry.getKey();
            double influence = entry.getValue();

            BiomeTerrainProvider provider = TerrainGenerationAPI.getTerrainProvider(biome);
            if (provider != null) {
                double customDensity = provider.getTerrainDensity(worldX, y, worldZ, vanillaDensity, influence, randomState);
                totalDensity = Mth.lerp(influence, totalDensity, customDensity);
            }
        }

        return totalDensity;
    }

    /**
     * Phase 3: Apply custom blocks with biome-based blending
     */
    private static void applyCustomBlocks(ChunkAccess chunk, RandomState randomState) {
        int minY = chunk.getMinBuildHeight();
        int maxY = chunk.getMaxBuildHeight();

        for (int x = 0; x < 16; x++) {
            for (int z = 0; z < 16; z++) {
                int worldX = chunk.getPos().getMinBlockX() + x;
                int worldZ = chunk.getPos().getMinBlockZ() + z;

                // Calculate biome influences
                Map<ResourceKey<Biome>, Double> biomeInfluences = calculateBiomeInfluences(chunk, x, z, worldX, worldZ);

                if (!biomeInfluences.isEmpty()) {
                    // Apply custom blocks to column
                    applyCustomBlocksToColumn(chunk, x, z, worldX, worldZ, biomeInfluences, randomState, minY, maxY);
                }
            }
        }
    }

    /**
     * Apply custom blocks to a single column
     */
    private static void applyCustomBlocksToColumn(ChunkAccess chunk, int x, int z, int worldX, int worldZ,
                                                  Map<ResourceKey<Biome>, Double> biomeInfluences,
                                                  RandomState randomState, int minY, int maxY) {

        // Find surface height
        int surfaceHeight = findSurfaceHeight(chunk, x, z, minY, maxY);

        for (int y = minY; y < maxY; y++) {
            BlockPos pos = new BlockPos(x, y, z);
            BlockState currentBlock = chunk.getBlockState(pos);

            // Skip air and water
            if (currentBlock.isAir() || currentBlock.is(Blocks.WATER)) {
                continue;
            }

            int depthFromSurface = surfaceHeight - y;
            BlockState newBlock = calculateCustomBlock(pos, currentBlock, biomeInfluences, depthFromSurface, randomState);

            if (!newBlock.equals(currentBlock)) {
                chunk.setBlockState(pos, newBlock, false);
            }
        }
    }

    /**
     * Calculate custom block with biome blending
     */
    private static BlockState calculateCustomBlock(BlockPos pos, BlockState vanillaBlock,
                                                   Map<ResourceKey<Biome>, Double> biomeInfluences,
                                                   int depthFromSurface, RandomState randomState) {

        BlockState resultBlock = vanillaBlock;
        double totalInfluence = 0.0;

        // Find the dominant biome influence
        ResourceKey<Biome> dominantBiome = null;
        double maxInfluence = 0.0;

        for (Map.Entry<ResourceKey<Biome>, Double> entry : biomeInfluences.entrySet()) {
            if (entry.getValue() > maxInfluence) {
                maxInfluence = entry.getValue();
                dominantBiome = entry.getKey();
            }
            totalInfluence += entry.getValue();
        }

        if (dominantBiome != null && maxInfluence > 0.3) {
            BiomeBlockProvider provider = TerrainGenerationAPI.getBlockProvider(dominantBiome);
            if (provider != null) {
                resultBlock = provider.getBlockState(pos, vanillaBlock, maxInfluence, depthFromSurface, randomState);
            }
        }

        return resultBlock;
    }

    /**
     * Calculate biome influences at a position with smooth blending
     */
    private static Map<ResourceKey<Biome>, Double> calculateBiomeInfluences(ChunkAccess chunk, int x, int z, int worldX, int worldZ) {
        Map<ResourceKey<Biome>, Double> influences = new HashMap<>();

        // Sample in a radius around the position
        int sampleRadius = 32;
        int sampleStep = 8;

        for (int dx = -sampleRadius; dx <= sampleRadius; dx += sampleStep) {
            for (int dz = -sampleRadius; dz <= sampleRadius; dz += sampleStep) {
                double distance = Math.sqrt(dx * dx + dz * dz);
                if (distance > sampleRadius) continue;

                // Calculate smooth weight
                double weight = 1.0 - (distance / sampleRadius);
                weight = smoothstep(weight); // Smooth interpolation

                try {
                    // Sample biome
                    int sampleX = worldX + dx;
                    int sampleZ = worldZ + dz;
                    ResourceKey<Biome> biome = getBiomeAtPosition(chunk, sampleX, sampleZ);

                    if (biome != null && TerrainGenerationAPI.hasCustomTerrain(biome)) {
                        influences.merge(biome, weight, Double::sum);
                    }
                } catch (Exception e) {
                    // Ignore sampling errors
                }
            }
        }

        // Normalize influences
        double totalInfluence = influences.values().stream().mapToDouble(Double::doubleValue).sum();
        if (totalInfluence > 0) {
            influences.replaceAll((biome, influence) -> influence / totalInfluence);
        }

        return influences;
    }

    /**
     * Get biome at world position
     */
    private static ResourceKey<Biome> getBiomeAtPosition(ChunkAccess chunk, int worldX, int worldZ) {
        try {
            int biomeX = (worldX >> 2) & 3; // Convert to biome coordinates within chunk
            int biomeZ = (worldZ >> 2) & 3;
            return chunk.getNoiseBiome(biomeX, 16, biomeZ).unwrapKey().orElse(null);
        } catch (Exception e) {
            return null;
        }
    }

    /**
     * Smooth interpolation function
     */
    private static double smoothstep(double t) {
        return t * t * (3.0 - 2.0 * t);
    }

    /**
     * Calculate vanilla density (simplified)
     */
    private static double calculateVanillaDensity(int worldX, int y, int worldZ, int surfaceHeight) {
        // Simplified density calculation - positive means solid, negative means air
        return surfaceHeight - y;
    }

    /**
     * Find surface height in chunk
     */
    private static int findSurfaceHeight(ChunkAccess chunk, int x, int z, int minY, int maxY) {
        for (int y = maxY - 1; y >= minY; y--) {
            BlockState state = chunk.getBlockState(new BlockPos(x, y, z));
            if (!state.isAir() && !state.is(Blocks.WATER)) {
                return y;
            }
        }
        return minY;
    }

    /**
     * Update heightmaps after terrain modification
     */
    private static void updateHeightmaps(ChunkAccess chunk) {
        for (int x = 0; x < 16; x++) {
            for (int z = 0; z < 16; z++) {
                int height = findSurfaceHeight(chunk, x, z, chunk.getMinBuildHeight(), chunk.getMaxBuildHeight());
                updateHeightmapsAt(chunk, x, z, height);
            }
        }
    }

    /**
     * Update heightmaps at specific position
     */
    private static void updateHeightmapsAt(ChunkAccess chunk, int x, int z, int height) {
        BlockPos pos = new BlockPos(x, height, z);
        BlockState state = chunk.getBlockState(pos);

        chunk.getOrCreateHeightmapUnprimed(Heightmap.Types.WORLD_SURFACE_WG)
                .update(x, height + 1, z, state);
        chunk.getOrCreateHeightmapUnprimed(Heightmap.Types.MOTION_BLOCKING)
                .update(x, height + 1, z, state);
        chunk.getOrCreateHeightmapUnprimed(Heightmap.Types.MOTION_BLOCKING_NO_LEAVES)
                .update(x, height + 1, z, state);
        chunk.getOrCreateHeightmapUnprimed(Heightmap.Types.OCEAN_FLOOR_WG)
                .update(x, height + 1, z, state);
    }
}